services:
   app:
       build:
           context: .
       image: dteam-django-test-task-cv_app
       ports:
           - "8000:8000"
       command: >
           sh -c "python manage.py wait_for_db &&
                  python manage.py migrate &&
                  python manage.py runserver 0.0.0.0:8000"
       env_file:
           - .env
       depends_on:
           - db
           - rabbitmq

       volumes:
           - ./:/app

   db:
       image: postgres:15
       restart: always
       ports:
           - "5432:5432"
       env_file:
           - .env
       volumes:
           - my_db:$PGDATA

   rabbitmq:
       image: rabbitmq:3-management
       ports:
           - "5672:5672"
           - "15672:15672"

   celery:
       build:
           context: .
       command: celery -A CVProject worker -l INFO
       env_file:
           - .env
       depends_on:
           - rabbitmq
           - db
       volumes:
           - ./:/app

volumes:
    my_db:
