# Generated by Django 5.2.1 on 2025-06-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cv",
            options={"ordering": ("id",)},
        ),
    ]
